---
apiVersion: batch/v1
kind: Job
metadata:
  name: secret-smuggler
spec:
  template:
    spec:
      serviceAccountName: "opi"
      restartPolicy: OnFailure
      containers:
      - name: smuggle
        image: eirini/secret-smuggler:{{ .Values.opi.image_tag }}
        env:
        - name: SECRET_NAME
          value: secrets-{{ .Values.scf.version }}-{{ .Values.scf.secrets_generation_counter }}
        - name: UAA_NAMESPACE
          value: uaa
        - name: SCF_NAMESPACE
          value: {{ .Release.Namespace }}
        - name: OPI_NAMESPACE
          value: {{ .Values.opi.namespace }}
        - name: REGISTRY_CREDS_SECRET_NAME
          value: {{ .Values.opi.registry_secret_name }}
        - name: REGISTRY_URL
          {{- if .Values.opi.use_registry_ingress }}
          value: "https://registry.{{ .Values.opi.ingress_endpoint }}:443"
          {{- else if .Values.services.loadbalanced }}
          value: "https://registry.{{ .Values.env.DOMAIN }}:6666"
          {{- else }}
          value: "https://registry.{{ index .Values.kube.external_ips 0 }}.nip.io:6666"
          {{- end }}
        - name: INTERNAL_CA_CERT
          valueFrom:
            secretKeyRef:
              name: secrets-{{ .Values.scf.version }}-{{ .Values.scf.secrets_generation_counter }}
              key: internal-ca-cert
        volumeMounts:
          - name: bits-config
            mountPath: /config
      volumes:
        - name: bits-config
          configMap:
            name: bits
            items:
              - key: bits-config-key
                path: bits-config
